### PR TITLE
VPA resources

### PR DESCRIPTION
**Pull request by njuettner**
Towards: https://github.com/giantswarm/roadmap/issues/3237

### CODE REVIEW

**Comment by QuentinBisson** [comment]
I'm a bit skeptical about metrics-server having VPA CRs though as VPA cannot function without metrics server running. Also, should @giantswarm/team-turtles not own metrics-server instead of atlas? This is more of a kubernetes metrics exporter that a monitoring tool

**Comment by QuentinBisson** [comment]
As long as we set correct min allowed, it should be alright but I'm afraid about the app chicken egg problem. I would think raising the limits could be a safe option as well, and maybe we need to adust the requests if it restarts often but that would require in-depth investigation

**Review by Gacko — APPROVED** [review]

**Comment by njuettner** [comment]
@QuentinBisson What do you suggest in regards to this PR? Shall we close then the PR for now?

**Comment by QuentinBisson** [comment]
Well, I'm not confident about this change but if you've tested it in a running cluster for a bit then we can go ahead

**Comment by njuettner** [comment]
Ok let me try to do some testing 👍🏻

**Comment by njuettner** [comment]
@QuentinBisson I tested it in CAPI, for me this seems good. I haven't seen any issues. If it's ok for you I'd like to merge it 🙂.

**Review by QuentinBisson — APPROVED** [review]

**Pull request merged**
